
name: Windows 10 - RustDesk (Safe)

on:
  workflow_dispatch:

jobs:
  build:
    name: Windows 10 Environment with RustDesk
    runs-on: windows-latest
    timeout-minutes: 360  # 6 ساعات وهو الحد الأقصى المسموح من GitHub

    steps:
      - name: إبقاء الجلسة نشطة (Anti-Idle)
        shell: powershell
        run: |
          Start-Job { while ($true) { Start-Sleep -Seconds 60; Write-Output "نشط..." } }

      - name: تحميل وتشغيل RustDesk من GitHub
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://github.com/rustdesk/rustdesk/releases/latest/download/rustdesk.exe" -OutFile "rustdesk.exe"
          Start-Process -FilePath ".\rustdesk.exe"

      - name: إشعار
        run: echo "تم تشغيل RustDesk بنجاح. الجلسة ستظل فعالة حتى 6 ساعات كحد أقصى."
